### ISSUE TITLE
Not suitable for 'real' desktops

### ISSUE THREAD

**Issue by theno1soco** [gitbls/RPiVNCHowTo#1]
I would suggest that for newbies to linux that a note at the beginning of this great howto is made:

The guide creates **virtual VNC desktops**, not attached to the HDMI console. It **does not allow connecting to the HDMI console** (the 'real desktop')

**Comment by gitbls** [comment]
Thanks for the suggestion. I've updated the README to note this. 

As an aside, I've started looking into connecting to the HDMI console physical desktop. I have a prototype working, but some exploration/experimentation still to be done.
