### ISSUE TITLE
Connecting to the HDMI console

### ISSUE THREAD

**Issue by theno1soco** [gitbls/RPiVNCHowTo#2]
What is the status of this please?

I am having disconnections using x11vnc.

**Comment by gitbls** [comment]
I was just planning to effectively "put a wrapper" around x11vnc, making it easier to configure and use. But, if x11vnc isn't stable, there's not much point in that! How is your system configured? Raspbian Lite vs Full, if Lite, what display manager are you using, how are you starting X if no display manager? And what is your current x11vnc command line?

**Comment by gitbls** [comment]
Closing due to no response.
