### ISSUE TITLE
RealVNC corrections/confirmation

### ISSUE THREAD

**Issue by CaptainMidnight** [gitbls/RPiVNCHowTo#3]
Just thought your RealVNC info needs a bit of a clarification: -

RealVNC does provide the ability for a cloud connection service BUT that is purely optional and not enabled unless you login/create a RealVNC account (which is also free to use for RPi use). Therefore is fully suitable and configurable to either a WAN or LAN deployment situation.

**Comment by gitbls** [comment]
Fair enough, and appropriate. I've clarified that. Thanks!
