### ISSUE TITLE
TigerVNC Virtual: Black Screen after Reboot

### ISSUE THREAD

**Issue by RadJKW** [gitbls/RPiVNCHowTo#6]
After (I believe properly) following all the instructions, i initially have access to ports 5901 and 5902. However, the screen is black. I then run <code> sudo systemctl restart lightdm.service</code> which fixes the issue temporarily. Every time i reboot the raspberry pi 4 i have to ssh into the device and restart the lightdm service. It works immediately after. 

># Device:
>## Raspberry PI 4 (4GB) Model B
> - **OS**: *Raspbian GNU/Linux 10 (buster)*
> - **CPU**: *5.10.60-v7l+*

**Comment by gitbls** [comment]
I'm going to need additional info to help you. 

- What version of Raspbian/RasPiOS? With desktop or Lite (specifically)
- Please provide from /etc/lightdm/lightdm.conf the line  [XDMCPServer] and the few lines following it before the next section (this should be what you edited in that config)
- Please provide the output from `sudo journalctl -b | grep lightdm`

**Comment by RadJKW** [comment]
### Details
- **Raspbian GNU/Linux 10 (buster)**
- ***lightdm.conf***

      [XDMCPServer] 
      enabled=true 
      port=177
      #listen-address=
      #key=
      #hostname=
      #VNC Server configuration

- *** journalctl output: ***

      Sep 15 13:29:18 RAD-RPI002 lightdm[675]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
      Sep 15 13:29:22 RAD-RPI002 lightdm[675]: warning: output VNC-0 not found; ignoring
      Sep 15 13:29:22 RAD-RPI002 lightdm[675]: warning: output VNC-0 not found; ignoring
      Sep 15 13:29:22 RAD-RPI002 lightdm[746]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
      Sep 15 13:29:22 RAD-RPI002 lightdm[746]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
      Sep 15 13:29:22 RAD-RPI002 systemd-logind[400]: New session c1 of user lightdm.
      Sep 15 13:29:22 RAD-RPI002 systemd[750]: pam_unix(systemd-user:session): session opened for user lightdm by (uid=0)
      Sep 15 13:29:22 RAD-RPI002 systemd[1]: Started Session c1 of user lightdm.
      Sep 15 13:29:30 RAD-RPI002 lightdm[789]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
      Sep 15 13:29:30 RAD-RPI002 systemd[1]: session-c1.scope: Killing process 746 (lightdm) with signal SIGTERM.
      Sep 15 13:29:30 RAD-RPI002 systemd[1]: Stopping Session c1 of user lightdm.
      Sep 15 13:29:30 RAD-RPI002 lightdm[746]: pam_unix(lightdm-greeter:session): session closed for user lightdm
      Sep 15 13:29:30 RAD-RPI002 systemd[1]: Stopped Session c1 of user lightdm.
      Sep 15 13:29:30 RAD-RPI002 lightdm[789]: pam_unix(lightdm:session): session opened for user pi by (uid=0)
      Sep 15 13:29:42 RAD-RPI002 lightdm[675]: Can't open display
      Sep 15 13:29:42 RAD-RPI002 lightdm[1204]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
      Sep 15 13:29:42 RAD-RPI002 lightdm[1204]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
      Sep 15 13:29:42 RAD-RPI002 systemd-logind[400]: New session c2 of user lightdm.
      Sep 15 13:29:42 RAD-RPI002 systemd[1208]: pam_unix(systemd-user:session): session opened for user lightdm by (uid=0)
      Sep 15 13:29:42 RAD-RPI002 systemd[1]: Started Session c2 of user lightdm.
      Sep 15 13:29:42 RAD-RPI002 lightdm[675]: Error activating login1 session: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: Operation not supported
      Sep 15 13:30:14 RAD-RPI002 lightdm[1236]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
      Sep 15 13:30:14 RAD-RPI002 systemd[1]: session-c2.scope: Killing process 1204 (lightdm) with signal SIGTERM.
      Sep 15 13:30:14 RAD-RPI002 systemd[1]: Stopping Session c2 of user lightdm.
      Sep 15 13:30:15 RAD-RPI002 lightdm[1204]: pam_unix(lightdm-greeter:session): session closed for user lightdm
      Sep 15 13:30:15 RAD-RPI002 systemd[1]: Stopped Session c2 of user lightdm.
      Sep 15 13:30:15 RAD-RPI002 lightdm[1236]: pam_unix(lightdm:session): session opened for user pi by (uid=0)
      Sep 15 13:30:15 RAD-RPI002 lightdm[675]: Error activating login1 session: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: Operation not supported
      Sep 15 13:31:04 RAD-RPI002 lightdm[1236]: pam_unix(lightdm:session): session closed for user pi
      Sep 15 13:33:20 RAD-RPI002 sudo[1451]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/nano /etc/lightdm/lightdm.conf

### Other Information: 
> I am running the full version of Raspian with Desktop
> I disabled RealVNC-server on port 5900 and attempted to run this unit 'Headless' so it would not boot into the desktop 
> - *To reduce resource consumption*
> Using this method is where i was having the black screen on vnc:5901
#### Changes that made it work: 
> - Set boot config for ***Desktop - Desktop GUI*** to require a login
> - <code>sudo systemctl enable vncserver-x11-serviced</code>
#### Conclusion
> - I am imagining that setting the pi to boot to console caused lightdm not to start
> - <code> sudo systemctl restart lightdm.service </code> maybe started the service
> - I would like to be able to logon to vnc:5901 with the raspberry pi configured as headless.

**Comment by gitbls** [comment]
So, your Pi does not have a graphical display on it. This causes lightdm to error out as seen here:
```
Sep 15 13:29:42 RAD-RPI002 lightdm[675]: Can't open display
```
The simple fix for this is to add `hdmi_force_hotplug=1` to /boot/config.txt and then reboot.

Please try this and  let me know the result.

**Comment by RadJKW** [comment]
From: /boot/config.txt
~~~
# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=2
hdmi_mode=69
~~~
I have had this enabled when i used RealVNC-server before attempting your virtual server tutorial. 
As i mentioned above in my huge mess of attempting markdown, 
> After booting to the headless configuration with realvnc disabled and no autologin,
> I run <code> sudo systemctl restart lightdm.service</code> , which fixes the issue.

**Comment by gitbls** [comment]
OK...so why is your lightdm service dying, as evidenced by the log you posted? What is causing these two errors?
```
Sep 15 13:29:22 RAD-RPI002 lightdm[675]: warning: output VNC-0 not found; ignoring
Sep 15 13:29:22 RAD-RPI002 lightdm[675]: warning: output VNC-0 not found; ignoring
```
I've never seen these in a configuration here. Have you added anything else to /etc/lightdm/lightdm.conf? 

My Pi-powered telepathy device isn't working at the moment. What else have you changed on your system?

**Comment by RadJKW** [comment]
I used your **.sh** files located in the repository for the system config edits. The raspberry pi has basically a fresh install. 
Ive also noticed that the virtual vnc servers are now lagging bad. I will attempt to remove everything and try again and possibly do a fresh install then update you if the problem persists.

**Comment by gitbls** [comment]
As I mentioned, I’ve never seen lightdm die like that, nor have I seen those two error messages from it. Something else, not related to this guide, changed something that is causing lightm a problem.

A clean install of RasPiOS and then installing per this guide will get you a working system.

Please let me know how it goes.

**Comment by gitbls** [comment]
jfyi I just did a complete build of 32-bit RasPiOS with desktop (2021-05-07) applied all updates, then ran `sudo make-systemd-xvnc`. I did not see those errors in the log and virtual VNC works correctly. 

Some change you made to your system has created this issue. One last thing to try: Get a "vanilla" /etc/lightdm/lightdm.conf, edit it per the documentation on this github, and reboot. I think this will correct your issue. You should be able to do `sudo apt-get reinstall lightdm` to get the "virgin" lightdm.conf back.

**Comment by gitbls** [comment]
@RadJKW Since you have not responded in over a week, I'm closing this issue. If needed, please feel free to re-open this issue or create a new one. Thanks.
